before:
  hooks:
    - go mod download
builds:
  - id: mtail
    main: ./cmd/mtail/main.go
    binary: mtail
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.Branch={{.Branch}}
      - -X main.Version={{.Version}}
      - -X main.Revision={{.Commit}}
    gcflags:
      # I love errors.
      - -e
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^Merge'
release:
  github:
  name_template: v{{.Version}}
dockers:
- image_templates: ["ghcr.io/google/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile.goreleaser
  use: buildx
  build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.ref.name="google/mtail"
    - --label=org.opencontainers.image.authors="Jamie Wilkinson (@jaqx0r)"
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.description="extract internal monitoring data from application logs for collection in a timeseries database"
    - --label=org.opencontainers.image.documentation="https://google.github.io/mtail/"
    - --label=org.opencontainers.image.licenses="Apache-2.0"
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.source=https://github.com/google/{{ .ProjectName }}
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/google/{{ .ProjectName }}
    - --label=org.opencontainers.image.vendor="Google"
    - --label=org.opencontainers.image.version={{ .Version }}
- image_templates: ["ghcr.io/google/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile.goreleaser
  use: buildx
  build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.ref.name="google/mtail"
    - --label=org.opencontainers.image.authors="Jamie Wilkinson (@jaqx0r)"
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.description="extract internal monitoring data from application logs for collection in a timeseries database"
    - --label=org.opencontainers.image.documentation="https://google.github.io/mtail/"
    - --label=org.opencontainers.image.licenses="Apache-2.0"
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.source=https://github.com/google/{{ .ProjectName }}
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/google/{{ .ProjectName }}
    - --label=org.opencontainers.image.vendor="Google"
    - --label=org.opencontainers.image.version={{ .Version }}
docker_manifests:
  - name_template: ghcr.io/google/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/google/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/google/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/google/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/google/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/google/{{ .ProjectName }}:{{ .Version }}-arm64v8
