name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  # golangci-lint does annotations, not comments
  # No-one knows what an annotation is, but I suspect it's printing file:line: msg to stdout.
  # https://github.community/t/what-are-annotations/16173/2
  checks: none

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v8
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.41

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
