name: "Close stale issues"
on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  pull-requests: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been waiting for more information for more than 60 days and will be closed in 7 if no update is provided.'
        stale-pr-message: 'This PR has been waiting for an update for more than 60 days and wlil be closed in 7 if no update is provided.'
        only-labels: 'more-info-needed'
